This commit was manufactured by cvs2git to create branch 'HLTrigger- Configuration-B32X'.
Sprout from master 2009-07-31 13:51:34 UTC Andrea Bocci <sha1-f43ac2238d9995f8c883948414432a9e5f50335c@cern.ch> 'update to /dev/CMSSW_3_2_2/HLT/V2'
Cherrypick from master 2009-08-18 13:18:43 UTC Andrea Bocci <sha1-f43ac2238d9995f8c883948414432a9e5f50335c@cern.ch> 'add support for 8E29 and 1E31 menus':
    tables/1E31.txt
    tables/8E29.txt
    tables/GRun.txt
    tables/makeSubTables
    test/add/Makefile
    test/cmsDriver.sh
    test/cmsDriver.sh.new
    test/cmsDriver.sh.old
    test/getHLT.py

diff --git a/test/add/Makefile b/test/add/Makefile
--- a/test/add/Makefile
+++ b/test/add/Makefile
@@ -7,17 +7,22 @@
 # 
 # run "make help" to get synopsis.
 #
-# Version 1.2.0, 1/7/2008
+# Version 1.3.2, 2009.08.18
 # Andrea Bocci <andrea.bocci@cern.ch>
 
 .PHONY: all list clean summary help
 
 # configuration goes here
-PROCESS:= HLT
-CONFIG := /dev/CMSSW_3_2_0/pre1/HLT
-SOURCE := file:$(CMSSW_BASE)/src/HLTrigger/Configuration/test/RelVal_Pure_Raw.root
-# /store/relval/2008/6/4/RelVal-RelValTTbar-1212543891-STARTUP-2nd/0000/185E7133-9C32-DD11-BC8E-001617E30CC8.root
-EVENTS := 100
+PROCESS := HLT
+EVENTS  := 100
+
+HLT_8E29_CONFIG     := /dev/CMSSW_3_2_2/8E29/V1
+HLT_8E29_GLOBALTAG  := STARTUP31X_V4::All
+HLT_8E29_SOURCE     := file:RelVal_DigiL1Raw_8E29.root
+
+HLT_1E31_CONFIG     := /dev/CMSSW_3_2_2/1E31/V1
+HLT_1E31_GLOBALTAG  := MC_31X_V5::All
+HLT_1E31_SOURCE     := file:RelVal_DigiL1Raw_1E31.root
 
 # more configuration, useful for debug the Makefile itself
 CMSRUN := cmsRun
@@ -37,23 +42,33 @@ YELLOW:= \033[33m
 BLUE  := \033[34m
 COLUMN:= \033[100G
 
-LIST_OF_PATHS:= $(shell edmConfigFromDB --configName $(CONFIG) --nopsets --noedsources --noes --noservices --nooutput --nosequences --nomodules --format python | gawk '/^process\..*(AlCa|HLT)_.* = cms.Path/ { print gensub(/^process\.(.*(AlCa|HLT)_.*) = cms.Path.*/, "\\1", 1) }' | sort)
-LIST_OF_PYS  := $(patsubst %, %.py, $(LIST_OF_PATHS))
-LIST_OF_LOGS := $(patsubst %, %.log, $(LIST_OF_PATHS))
-LIST_OF_DIFFS:= $(patsubst %, %.diff, $(LIST_OF_PATHS))
+LIST_OF_8E29_PATHS:= $(shell edmConfigFromDB --configName $(HLT_8E29_CONFIG) --nopsets --noedsources --noes --noservices --nooutput --nosequences --nomodules --format python | gawk '/^process\..*(AlCa|HLT)_.* = cms.Path/ { print gensub(/^process\.(.*(AlCa|HLT)_.*) = cms.Path.*/, "\\1", 1) }' | sort)
+LIST_OF_8E29_PYS  := $(patsubst %, 8E29_%.py,   $(LIST_OF_8E29_PATHS))
+LIST_OF_8E29_LOGS := $(patsubst %, 8E29_%.log,  $(LIST_OF_8E29_PATHS))
+LIST_OF_8E29_DIFFS:= $(patsubst %, 8E29_%.diff, $(LIST_OF_8E29_PATHS))
+
+LIST_OF_1E31_PATHS:= $(shell edmConfigFromDB --configName $(HLT_1E31_CONFIG) --nopsets --noedsources --noes --noservices --nooutput --nosequences --nomodules --format python | gawk '/^process\..*(AlCa|HLT)_.* = cms.Path/ { print gensub(/^process\.(.*(AlCa|HLT)_.*) = cms.Path.*/, "\\1", 1) }' | sort)
+LIST_OF_1E31_PYS  := $(patsubst %, 1E31_%.py,   $(LIST_OF_1E31_PATHS))
+LIST_OF_1E31_LOGS := $(patsubst %, 1E31_%.log,  $(LIST_OF_1E31_PATHS))
+LIST_OF_1E31_DIFFS:= $(patsubst %, 1E31_%.diff, $(LIST_OF_1E31_PATHS))
+
+LIST_OF_PATHS:= $(shell echo $(LIST_OF_8E29_PATHS) $(LIST_OF_1E31_PATHS) | xargs -n1 echo | sort -u)
+LIST_OF_PYS  := $(LIST_OF_8E29_PYS)   $(LIST_OF_1E31_PYS)
+LIST_OF_LOGS := $(LIST_OF_8E29_LOGS)  $(LIST_OF_1E31_LOGS)
+LIST_OF_DIFFS:= $(LIST_OF_8E29_DIFFS) $(LIST_OF_1E31_DIFFS)
 
 .PHONY: $(LIST_OF_PATHS)
 
-all: pys logs diffs summary
+all:    pys logs diffs summary
 
-pys: Global_Table.py $(LIST_OF_PYS)
+pys:    8E29_GlobalTable.py   1E31_GlobalTable.py   $(LIST_OF_PYS)
 
-logs: Global_Table.log $(LIST_OF_LOGS)
+logs:   8E29_GlobalTable.log  1E31_GlobalTable.log  $(LIST_OF_LOGS)
 
-diffs: Global_Table.log $(LIST_OF_DIFFS)
+diffs:  8E29_GlobalTable.diff 1E31_GlobalTable.diff $(LIST_OF_DIFFS)
 
 clean:
-	@rm -f .database .dataset *.py *.pyc *.log *.diff *.root
+	@rm -f .database_* .dataset_* *.py *.pyc *.log *.diff HLT*.root AlCa*.root
   
 list: 
 	@echo "$(LIST_OF_PATHS)"
@@ -68,7 +83,9 @@ summary:
 	  for P in $$DIFF; do echo -e "\t$(RED)$$P$(NORMAL)"; done; \
 	  echo; \
 	fi
-	@PARTIAL=$$(gawk 'FNR==1 { NAME=gensub(/(.*)\.log/,"\\1",1,FILENAME); HEADER="TrigReport ---------- Modules in Path: "NAME" ------------"; } $$0 ~ HEADER { while ($$0 !~ /TrigReport.*hltBoolEnd/) getline; if ($$5 == 0) print NAME; nextfile; }' *_*.log); \
+	@DIFF=`ls *.diff | sed -e's/\.diff$$//'`; \
+	PARTIAL=$$(gawk 'FNR==1 { NAME=gensub(/(.*)\.log/,"\\1",1,FILENAME); HEADER="TrigReport ---------- Modules in Path: "NAME" ------------"; } $$0 ~ HEADER { while ($$0 !~ /TrigReport.*hltBoolEnd/) getline; if ($$5 == 0) print NAME; nextfile; }' *_*.log); \
+        PARTIAL=$$(for P in $$PARTIAL; do echo $$DIFF | grep -q $$P || echo $$P; done); \
 	if [ -z "$$PARTIAL" ]; then \
 	  echo "All paths where fully excercised."; \
 	else \
@@ -78,31 +95,53 @@ summary:
 	fi
 
 # these are kinda tricky: we need rules based on the file content, not on its modification date
-ifneq ($(CONFIG),$(shell [ -f .database ] && cat .database))
-.database:
-	@echo $(CONFIG) > .database
+DB_8E29_NEW:=$(shell echo -e "CONFIG=$(HLT_8E29_CONFIG)\nSOURCE=$(HLT_8E29_SOURCE)\nGLOBALTAG=$(HLT_8E29_GLOBALTAG)" | md5sum | cut -c -32)
+DB_8E29_SUM:=$(shell [ -f .database_8E29 ] && cat .database_8E29 | md5sum | cut -c -32)
+
+ifneq ($(DB_8E29_NEW), $(DB_8E29_SUM))
+.database_8E29:
+	@echo -e "CONFIG=$(HLT_8E29_CONFIG)\nSOURCE=$(HLT_8E29_SOURCE)\nGLOBALTAG=$(HLT_8E29_GLOBALTAG)" > .database_8E29
 endif
 
-ifneq ($(SOURCE),$(shell [ -f .dataset ] && cat .dataset))
-.dataset:
-	@echo $(SOURCE) > .dataset
+DB_1E31_NEW:=$(shell echo -e "CONFIG=$(HLT_1E31_CONFIG)\nSOURCE=$(HLT_1E31_SOURCE)\nGLOBALTAG=$(HLT_1E31_GLOBALTAG)" | md5sum | cut -c -32)
+DB_1E31_SUM:=$(shell [ -f .database_1E31 ] && cat .database_1E31 | md5sum | cut -c -32)
+
+ifneq ($(DB_1E31_NEW), $(DB_1E31_SUM))
+.database_1E31:
+	@echo -e "CONFIG=$(HLT_1E31_CONFIG)\nSOURCE=$(HLT_1E31_SOURCE)\nGLOBALTAG=$(HLT_1E31_GLOBALTAG)" > .database_1E31
 endif
+
 # end of tricky rules
 
-Global_Table.py: .database .dataset
-	@echo -e " ConfDB [$(BLUE)$(CONFIG)$(NORMAL)] ---- $(BOLD)Global_Table$(NORMAL)"
-	@$(GETCONFIG) --configName $(CONFIG) --input $(SOURCE) --services -PrescaleService --format python | sed -e's/^process = cms.Process(.*)/process = cms.Process( "$(PROCESS)" )/' -e's/^process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( $(EVENTS) ) )/process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( 100 ) )/' > Global_Table.py
-#	@echo -e "$(COLUMN)$(GREEN)done$(NORMAL)"
+8E29_GlobalTable.py: .database_8E29
+	@echo -e " ConfDB [$(BLUE)$(HLT_8E29_CONFIG)$(NORMAL)] menu $(BOLD)8E29_GlobalTable$(NORMAL)"
+	@$(GETCONFIG) --configName $(HLT_8E29_CONFIG) --input $(HLT_8E29_SOURCE) --nooutput --services -PrescaleService --format python | sed -e's/^process = cms.Process(.*)/process = cms.Process( "$(PROCESS)" )/' -e's/^process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( $(EVENTS) ) )/process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( 100 ) )/' > 8E29_GlobalTable.py
+	@echo -e "process.GlobalTag.globaltag = \"$(HLT_8E29_GLOBALTAG)\"" >> 8E29_GlobalTable.py
 
-Global_Table.log: Global_Table.py
-	@echo -n "running Global Table"
-	@$(CMSRUN) Global_Table.py >& Global_Table.log
+1E31_GlobalTable.py: .database_1E31
+	@echo -e " ConfDB [$(BLUE)$(HLT_1E31_CONFIG)$(NORMAL)] menu $(BOLD)1E31_GlobalTable$(NORMAL)"
+	@$(GETCONFIG) --configName $(HLT_1E31_CONFIG) --input $(HLT_1E31_SOURCE) --nooutput --services -PrescaleService --format python | sed -e's/^process = cms.Process(.*)/process = cms.Process( "$(PROCESS)" )/' -e's/^process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( $(EVENTS) ) )/process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( 100 ) )/' > 1E31_GlobalTable.py
+	@echo -e "process.GlobalTag.globaltag = \"$(HLT_1E31_GLOBALTAG)\"" >> 1E31_GlobalTable.py
+
+8E29_GlobalTable.log: 8E29_GlobalTable.py
+	@echo -n "running 8E29 Global Table"
+	@$(CMSRUN) 8E29_GlobalTable.py >& 8E29_GlobalTable.log
 	@echo -e "$(COLUMN)$(GREEN)done$(NORMAL)"
 
-$(LIST_OF_PYS): %.py: .database .dataset
-	@echo -e " ConfDB [$(BLUE)$(CONFIG)$(NORMAL)] path $(BOLD)$*$(NORMAL)"
-	@$(GETCONFIG) --configName $(CONFIG) --input $(SOURCE) --paths HLTriggerFirstPath,$*,HLTriggerFinalPath --services -PrescaleService --format python | sed -e's/^process = cms.Process(.*)/process = cms.Process( "$(PROCESS)" )/' -e's/^process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( $(EVENTS) ) )/process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( 100 ) )/' > $@
-#	@echo -e "$(COLUMN)$(GREEN)done$(NORMAL)"
+1E31_GlobalTable.log: 1E31_GlobalTable.py
+	@echo -n "running 1E31 Global Table"
+	@$(CMSRUN) 1E31_GlobalTable.py >& 1E31_GlobalTable.log
+	@echo -e "$(COLUMN)$(GREEN)done$(NORMAL)"
+
+$(LIST_OF_8E29_PYS): %.py: .database_8E29
+	@echo -e " ConfDB [$(BLUE)$(HLT_8E29_CONFIG)$(NORMAL)] path $(BOLD)$*$(NORMAL)"
+	@$(GETCONFIG) --configName $(HLT_8E29_CONFIG) --input $(HLT_8E29_SOURCE) --paths HLTriggerFirstPath,$*,HLTriggerFinalPath --services -PrescaleService --format python | sed -e's/^process = cms.Process(.*)/process = cms.Process( "$(PROCESS)" )/' -e's/^process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( $(EVENTS) ) )/process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( 100 ) )/' > $@
+	@echo -e "process.GlobalTag.globaltag = \"$(HLT_8E29_GLOBALTAG)\"" >> $@
+
+$(LIST_OF_1E31_PYS): %.py: .database_1E31
+	@echo -e " ConfDB [$(BLUE)$(HLT_1E31_CONFIG)$(NORMAL)] path $(BOLD)$*$(NORMAL)"
+	@$(GETCONFIG) --configName $(HLT_1E31_CONFIG) --input $(HLT_1E31_SOURCE) --paths HLTriggerFirstPath,$*,HLTriggerFinalPath --services -PrescaleService --format python | sed -e's/^process = cms.Process(.*)/process = cms.Process( "$(PROCESS)" )/' -e's/^process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( $(EVENTS) ) )/process.maxEvents = cms.untracked.PSet(  input = cms.untracked.int32( 100 ) )/' > $@
+	@echo -e "process.GlobalTag.globaltag = \"$(HLT_1E31_GLOBALTAG)\"" >> $@
 
 $(LIST_OF_LOGS): %.log: %.py
 	@echo -n "running trigger path $*"
@@ -111,12 +150,26 @@ $(LIST_OF_LOGS): %.log: %.py
 
 $(LIST_OF_PATHS): %: %.diff
 
-$(LIST_OF_DIFFS): Global_Table.log
+$(LIST_OF_8E29_DIFFS): 8E29_GlobalTable.log
 
-$(LIST_OF_DIFFS): %.diff: %.log
+$(LIST_OF_1E31_DIFFS): 1E31_GlobalTable.log
+
+$(LIST_OF_8E29_DIFFS): %.diff: %.log
 	@echo -n "checking trigger path $*"
-	@cat $*.log         | gawk 'BEGIN { FOUND=0 } /TrigReport ---------- Modules in Path: $* ------------/ { FOUND=1; print; getline; print "TrigReport  Trig    Visited     Passed     Failed      Error Name"; next; } /^$$/ {FOUND=0; next; } // { if (FOUND) printf "TrigReport   %3d %10d %10d %10d %10d %s\n",$$2,$$4,$$5,$$6,$$7,$$8 }' > $*.single
-	@cat Global_Table.log | gawk 'BEGIN { FOUND=0 } /TrigReport ---------- Modules in Path: $* ------------/ { FOUND=1; print; getline; print "TrigReport  Trig    Visited     Passed     Failed      Error Name"; next; } /^$$/ {FOUND=0; next; } // { if (FOUND) printf "TrigReport   %3d %10d %10d %10d %10d %s\n",$$2,$$4,$$5,$$6,$$7,$$8 }' > $*.full
+	@cat $*.log               | gawk 'BEGIN { FOUND=0 } /TrigReport ---------- Modules in Path: $* ------------/ { FOUND=1; print; getline; print "TrigReport  Trig    Visited     Passed     Failed      Error Name"; next; } /^$$/ {FOUND=0; next; } // { if (FOUND) printf "TrigReport   %3d %10d %10d %10d %10d %s\n",$$2,$$4,$$5,$$6,$$7,$$8 }' > $*.single
+	@cat 8E29_GlobalTable.log | gawk 'BEGIN { FOUND=0 } /TrigReport ---------- Modules in Path: $* ------------/ { FOUND=1; print; getline; print "TrigReport  Trig    Visited     Passed     Failed      Error Name"; next; } /^$$/ {FOUND=0; next; } // { if (FOUND) printf "TrigReport   %3d %10d %10d %10d %10d %s\n",$$2,$$4,$$5,$$6,$$7,$$8 }' > $*.full
+	@if diff -w -U 999 $*.full $*.single > $*.diff; then \
+            rm -f $*.diff; \
+            echo -e "$(COLUMN)$(GREEN)done$(NORMAL)"; \
+        else \
+            echo -e "$(COLUMN)$(RED)error$(NORMAL)"; \
+        fi
+	@rm -f $*.single $*.full
+
+$(LIST_OF_1E31_DIFFS): %.diff: %.log
+	@echo -n "checking trigger path $*"
+	@cat $*.log               | gawk 'BEGIN { FOUND=0 } /TrigReport ---------- Modules in Path: $* ------------/ { FOUND=1; print; getline; print "TrigReport  Trig    Visited     Passed     Failed      Error Name"; next; } /^$$/ {FOUND=0; next; } // { if (FOUND) printf "TrigReport   %3d %10d %10d %10d %10d %s\n",$$2,$$4,$$5,$$6,$$7,$$8 }' > $*.single
+	@cat 1E31_GlobalTable.log | gawk 'BEGIN { FOUND=0 } /TrigReport ---------- Modules in Path: $* ------------/ { FOUND=1; print; getline; print "TrigReport  Trig    Visited     Passed     Failed      Error Name"; next; } /^$$/ {FOUND=0; next; } // { if (FOUND) printf "TrigReport   %3d %10d %10d %10d %10d %s\n",$$2,$$4,$$5,$$6,$$7,$$8 }' > $*.full
 	@if diff -w -U 999 $*.full $*.single > $*.diff; then \
             rm -f $*.diff; \
             echo -e "$(COLUMN)$(GREEN)done$(NORMAL)"; \
@@ -127,34 +180,32 @@ $(LIST_OF_DIFFS): %.diff: %.log
 
 help:
 	@echo 'This makefile checks that each trigger path gives the same results if run stand-alone or in the global trigger table.'
-	@echo 'Given a configName, it extracts from ConfDB the global table (Global_Table.py), the list of path, and a configuration'
+	@echo 'Given a configName, it extracts from ConfDB the global table (*.py_GlobalTable), the list of path, and a configuration'
 	@echo 'for each path (TriggerName.py).'
 	@echo 'Then both the trigger table and each paths are run, the corresponding TrigReport is extracted from the log, and compared.'
-	@echo ''
+	@echo
 	@echo 'After running each path, a warning is issued if a path is not fully excersided, i.e. no events pass all the filters.'
 	@echo 'After comparing with the global table, an error is issued if there are discrepenaices in the TrigReport (at any level).'
-	@echo ''
+	@echo
 	@echo 'Working files:'
-	@echo '  .database           configuration name, as looked for in ConfDB'
-	@echo '  .dataset            dataset filename, used in PoolSource'
-	@echo '  Global_Table.py     configuration for the global table'
-	@echo '  Global_Table.log    output of cmsRun Global_Table.py'
-	@echo '  TriggerName.py      configuration for TriggerName path'
-	@echo '  TriggerName.log     output of cmsRun TriggerName.py'
-	@echo '  TriggerName.diff    differences between TrigReport for TriggerName between global table run and stand-alone run'
-	@echo ''
+	@echo '  .database_LUMI         running conditions: ConfDB configuration, input dataset, GlobalTag'
+	@echo '  LUMI_GlobalTable.py    configuration for the global table'
+	@echo '  LUMI_GlobalTable.log   output of cmsRun LUMI_GlobalTable.py'
+	@echo '  TriggerName.py         configuration for TriggerName path'
+	@echo '  TriggerName.log        output of cmsRun TriggerName.py'
+	@echo '  TriggerName.diff       differences between TrigReport for TriggerName between global table run and stand-alone run'
+	@echo
 	@echo 'Supported targets:'
-	@echo '  all                 same as "cfgs logs diffs summary"'
-	@echo '  list                list all trigger paths'
-	@echo '  pys                 extract all (python) configuration files'
-	@echo '  logs                run all configuration files'
-	@echo '  diffs               extract all differences'
-	@echo '  summary             analyze all *available* diff and log files to print the list of trigger paths with discrepancies and/or with no accepted events'
-	@echo '  help                print a simple description of this tool'
-	@echo ''
-	@echo '  TriggerName         run the full chain for trigger TriggerName: extract TriggerName.py, cmsRun logging to TriggerName.log,'
-	@echo '                      if necessary extract and run the global table, and compare the TrigResults.'
-	@echo ''
-	@echo ''
-	@echo 'Version 1.2.0, 1/7/2008'
+	@echo '  all                    same as "pys logs diffs summary"'
+	@echo '  list                   list all trigger paths'
+	@echo '  pys                    extract all (python) configuration files'
+	@echo '  logs                   run all configuration files'
+	@echo '  diffs                  extract all differences'
+	@echo '  summary                analyze all *available* diff and log files to print the list of trigger paths with discrepancies and/or with no accepted events'
+	@echo '  help                   print a simple description of this tool'
+	@echo
+	@echo '  TriggerName            run the full chain for trigger TriggerName: extract TriggerName.py, cmsRun logging to TriggerName.log,'
+	@echo '                         if necessary extract and run the global table, and compare the TrigResults.'
+	@echo
+	@echo 'Version 1.3.2, 2009.08.18'
 	@echo 'Andrea Bocci <andrea.bocci@cern.ch>'
